function [waterEquivDose_SourceToIsocentre, waterEquivDose_IsocentreToEPID] = runWaterEquivalentDoseCalculations(pointSourceCoords, pointDetectorCoords, ctVoxelDimsInM, ctDataLocationInM, ctDataSet, sourceToAxisInM, axisToEpidInM)
% [waterEquivDose_SourceToIsocentre, waterEquivDose_IsocentreToEPID] = runWaterEquivalentDoseCalculations(pointSourceCoords, pointDetectorCoords, ctVoxelDimsInM, ctDataLocationInM, ctDataSet, sourceToAxisInM, axisToEpidInM)

dims = size(ctDataSet);

ctDataSetDims = [dims(2), dims(1), dims(3)];

if Constants.Use_Mex_Code
    fn = @(sourceCoordsX, sourceCoordsY, sourceCoordsZ, detectorCoordsX, detectorCoordsY, detectorCoordsZ)...
        fastRayTrace_mex(...
        [sourceCoordsX, sourceCoordsY, sourceCoordsZ],...
        [detectorCoordsX, detectorCoordsY, detectorCoordsZ],...
        ctDataLocationInM, ctDataSetDims, ctVoxelDimsInM,...
        ctDataSet,...
        sourceToAxisInM, axisToEpidInM);
else
    fn = @(sourceCoordsX, sourceCoordsY, sourceCoordsZ, detectorCoordsX, detectorCoordsY, detectorCoordsZ)...
        fastRayTrace(...
        [sourceCoordsX, sourceCoordsY, sourceCoordsZ],...
        [detectorCoordsX, detectorCoordsY, detectorCoordsZ],...
        ctDataLocationInM, ctDataSetDims, ctVoxelDimsInM,...
        ctDataSet,...
        sourceToAxisInM, axisToEpidInM);
end

[waterEquivDose_SourceToIsocentre, waterEquivDose_IsocentreToEPID] = arrayfun(fn,...
    pointSourceCoords(:,1),...
    pointSourceCoords(:,2),...
    pointSourceCoords(:,3),...
    pointDetectorCoords(:,1),...
    pointDetectorCoords(:,2),...
    pointDetectorCoords(:,3));

end

